### ISSUE TITLE
각 레이블의 정의가 모호한거 같아서 이슈를 남깁니다.

### ISSUE THREAD

**Issue by sda96** [tunib-ai/DKTC#1]
안녕하세요. 
현재 AIFFEL 3차 해커톤을 진행중인 대전2기 박창현입니다.
DKTC 데이터셋 분석중에 의문이 생겨서 이슈를 남깁니다.

분류 모델을 사용해서 DKTC 데이터셋의 위협문장 레이블을 분류하는데 유독 제대로 분류하지 못하는 데이터가 존재하는거 같습니다.
분류 모델이 제대로 분류하지 못한 경우를 담은 엑셀파일도 링크를 남깁니다.  [오분류예제.xlsx](https://github.com/tunib-ai/DKTC/files/8021988/default.xlsx)

오분류예제들을 보면 보는 사람의 관점에 따라서 다르게 해석될 수 있는 데이터가 존재하며, 특히 기타 괴롭힘 대화가 가진 정의가 모호해서 생기는 문제라고 생각됩니다.
각 레이블, 협박 대화, 갈취 대화, 직장 내 괴롭힘 대화, 기타 괴롭힘 대화, 총 4가지의 레이블에 대한 명확한 정의를 알려주셨으면 합니다.

**Comment by sooftware** [comment]
<img width="207" alt="image" src="https://user-images.githubusercontent.com/42150335/152967827-710fde54-d905-480c-a027-1420ace22515.png">
  
저희가 참여했던 그랜드챌린지 대회의 레이블 정의서를 첨부합니다.  
도움이 됐으면 좋겠습니다.  
정의된 기준이 있지만 데이터마다 애매한 경우가 있고, 레이블링 작업자에 따라서도 약간의 바이어스가 있을 수 있는 점 이해 부탁드립니다.

**Comment by sda96** [comment]
답변 감사합니다! 이슈는 종료하겠습니다.
