### ISSUE TITLE
test.json 파일에 관련된 이슈입니다.

### ISSUE THREAD

**Issue by sda96** [tunib-ai/DKTC#2]
안녕하세요. 아이펠 대전2기 박창현입니다.
현재 DKTC 데이터셋을 분석하고 test.json 파일을 살펴보는중에 이상하다고 생각되어 이슈를 남깁니다.

Q1. : 현 repository의 readme 내용을 보면 test 데이터의 개수가 500개로 나와있는데 실제 test.json에 있는 데이터의 개수는 400개로 나옵니다. 어느 내용이 잘못된건지 확인 부탁드립니다.

Q2 : test.json 파일의 index가 순서대로가 아닌거 같습니다.
![image](https://user-images.githubusercontent.com/51338268/153363551-1e8cf07f-986c-4e53-8802-975a404f8a6a.png)
index가 그림과 같이 0부터 순서대로가 아니라 중간에 빠진 숫자로 인해서 index가 밀리는 현상이 있습니다.
이 현상을 일부러 의도하신건지 아니면 착오가 있는건지 여쭤보고 싶었습니다.
해당 repository의 data파일에 있는 test.json 파일 확인 부탁드립니다.

검토 부탁드립니다. 감사합니다.

**Comment by sooftware** [comment]
확인하고 조치중입니다.
감사합니다.

**Comment by sooftware** [comment]
데이터에 일부 누락된걸 확인해서 조치했습니다 :)
감사합니다!

**Comment by sda96** [comment]
조치 감사합니다!
